---
deployment:
  tasks:
    - export NODE_ENV=production

    # Step 1: Use the locally installed Node.js version (v20)
    - export PATH=/local/node/bin:$PATH

    # Step 2: Install dependencies for the project
    - /local/node/bin/npm install

    # Step 3: Build the React project
    - /local/node/bin/npm run build

    # Step 4: Copy the build files to the public_html directory
    - rsync -av --delete-after dist/ ~/test/

    # Step 5: Clean up any unnecessary files in public_html
    - find ~/public_html/ -type f -name "*.map" -delete
