export const cardContent = [
  {
    id: "1",
    description: "Hackathon",
    title: "Kleos 2.0",
    date: "📆: 21 Jun to 23 Jun 2024",
    src: "/images/events/kleosupcoming.jpg",
    content: `RAIT ACM, RAIT ACM W, and DY Patil University conducted a national-level hackathon. Students from all over India [more than 16 states] participated, and the prize pool was 20 LAKHS INR including a cash prize of 50k INR.`,
  },
  {
    id: "2",
    description: "Speaker Session",
    title: "How to win a Hackathon",
    date: "📆: 14 Mar 2024",
    src: "/images/events/esp2.jpg",
    content: `RAIT-ACM presented EMINENT SPEAKER PROGRAM 2024 on 13th&14th March 2024. Second day session was on "How to Win a Hackathon?" which was presented by Dr. Prashant R. Nair .Who is Head & Vice-Chairman, IQAC of Amrita Vishwa Vidyapeetham, Coimbatore, India and Author of 6 books, 2 edited books, and over 50 publications in reputed journals, books, and conferences. Dr. Prashant R. Nair gave Strategies to ace hackathons. Discussing how teams should be formed and to contest selection for a team, Winning online & onsite hackathons and Mastering hardware & software challenges in modern hackathons.`,
  },
  {
    id: "3",
    description: "Speaker Session",
    title: "A Time Traversal through AI Eras",
    date: "📆: 13 Mar 2024",
    src: "/images/events/esp1.jpg",
    content: `RAIT-ACM presented EMINENT SPEAKER PROGRAM 2024 on 13th March 2024. First day session was on "A Time-Traversal through AI Eras"which was presented by Dr.Aritra Hazra.Who is a Ph.D. in Computer Science and Engineering and is a Assistant Professor at the Indian Institute of Technology (IIT) Kharagpur. Dr.Aritra Hazra gave insights on Breakthroughs in mastering strategic games also making Complex decision-making against opponents in a live game. Also Achieving expert-level performance in difficult situations during gaming. Alas, how Dominance of AI and how examples of AI surpassing human abilities.`,
  },
  {
    id: "4",
    description: "Speaker Session",
    title: "STREE-SPURTI",
    date: "📆: 07 Mar 2024",
    src: "/images/events/streespurti.webp",
    content: `A fun event on the occasion of Women's Week for teachers.`,
  },
  {
    id: "5",
    description: "Speaker Session",
    title: "HEALTH & HYGIENE",
    date: "📆: 06 Mar 2024",
    src: "/images/events/Hygiene-M.png",
    content: `A speaker session on the occasion of Women's Week by an expert. This helped to understand the body better, make smart health choices & take charge of your well-being. It helped to learn effective oral hygiene practices and habits.`,
  },
  {
    id: "6",
    description: "Competition",
    title: "EXTEMPORE COMPETITION",
    date: "📆: 06 Mar 2024",
    src: "/images/events/Ext-Comp-Banner.webp",
    content: `A competition on the occasion of Women's Week by an expert. This competition helps participants to get an opportunity to express opinions, exude confidence, and let words speak for themselves.`,
  },
  {
    id: "7",
    description: "Speaker Sessions",
    title: "CYBER CONCLAVE",
    date: "📆: 01 Mar to 02 Mar 2024",
    src: "/images/events/cyberconclave.jpg",
    content: `Conclave helped students dive into the world of cybersecurity with the most anticipated event of the year! Participants gained knowledge from industry leaders and networking with like-minded professionals.`,
  },
  {
    id: "8",
    description: "Industry Program",
    title: "CyberSecurity & Digital Forensics",
    date: "📆: 01 Jan to 06 Jan 2024",
    src: "/images/events/cybersectraining.webp",
    content: `Elevated your expertise with exclusive sessions led by industry-level professionals, designed to boost your technical skills. Dived into hands-on project development and received evaluations from domain experts. Organized by the Department of Information Technology in collaboration with RAIT ACM, RAIT ACM-W, and IIC, the Industrial Training Program 2024 focused on Cyber Security and Digital Forensics has successfully concluded. Stay tuned for more upcoming opportunities to advance your knowledge and excel in the ever-evolving tech landscape!`,
  },
];
